/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AccountManager;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.AccountDirectory;

/**
 *
 * @author hardishah
 */
public class AccountMngWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    AccountDirectory accountDirectory;
    /**
     * Creates new form AccountMngWorkAreaJPanel
     */
    public AccountMngWorkAreaJPanel(JPanel container, AccountDirectory directory) {
        initComponents();
        
        userProcessContainer = container;
        accountDirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnCreateAccount = new javax.swing.JButton();
        jbtnManageAccount = new javax.swing.JButton();

        jbtnCreateAccount.setText("Create Account");
        jbtnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreateAccountActionPerformed(evt);
            }
        });

        jbtnManageAccount.setText("Manage Account");
        jbtnManageAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnManageAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnManageAccount)
                    .addComponent(jbtnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jbtnCreateAccount)
                .addGap(108, 108, 108)
                .addComponent(jbtnManageAccount)
                .addContainerGap(261, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateAccountActionPerformed
        // TODO add your handling code here:
        
        CreateAccountJPanel panel = new CreateAccountJPanel(userProcessContainer, accountDirectory);
        userProcessContainer.add ("CreateAccountJPanel", panel) ;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next (userProcessContainer);
    }//GEN-LAST:event_jbtnCreateAccountActionPerformed

    private void jbtnManageAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnManageAccountActionPerformed
        // TODO add your handling code here:
        ManageAccountsJPanel panel1 = new ManageAccountsJPanel(userProcessContainer, accountDirectory);
        userProcessContainer.add ("ManageAccountsJPanel", panel1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout ();
        layout.next(userProcessContainer) ;
    }//GEN-LAST:event_jbtnManageAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCreateAccount;
    private javax.swing.JButton jbtnManageAccount;
    // End of variables declaration//GEN-END:variables
}
