/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AccountManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Account;
import model.AccountDirectory;

/**
 *
 * @author hardishah
 */
public class CreateAccountJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    AccountDirectory accountDirectory;
    /**
     * Creates new form CreateAccountJPanel
     */
    public CreateAccountJPanel(JPanel container, AccountDirectory directory) {
        initComponents();
        userProcessContainer = container;
        accountDirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jlblRoutingNumber = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jlblAccountNumber = new javax.swing.JLabel();
        jlblBankName = new javax.swing.JLabel();
        jlblBalance = new javax.swing.JLabel();
        jtxtRoutingNumber = new javax.swing.JTextField();
        jtxtAccountNumber = new javax.swing.JTextField();
        jtxtBankName = new javax.swing.JTextField();
        jtxtBalance = new javax.swing.JTextField();
        jbtnCreate = new javax.swing.JButton();

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jlblRoutingNumber.setText("Routing Number");

        lblTitle.setText("Create Account");

        jlblAccountNumber.setText("Account Number");

        jlblBankName.setText("Bank Name");

        jlblBalance.setText("Balance");

        jtxtAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAccountNumberActionPerformed(evt);
            }
        });

        jtxtBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBankNameActionPerformed(evt);
            }
        });

        jbtnCreate.setText("Create Account");
        jbtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblRoutingNumber)
                    .addComponent(jlblAccountNumber)
                    .addComponent(jlblBankName)
                    .addComponent(jlblBalance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtRoutingNumber)
                    .addComponent(jtxtAccountNumber)
                    .addComponent(jtxtBankName)
                    .addComponent(jtxtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addComponent(jbtnCreate)
                        .addGap(253, 253, 253))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(lblTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnBack))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblRoutingNumber)
                    .addComponent(jtxtRoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAccountNumber)
                    .addComponent(jtxtAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblBankName)
                    .addComponent(jtxtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblBalance)
                    .addComponent(jtxtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jbtnCreate)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateActionPerformed
        // TODO add your handling code here:
        int balance;
        String routingNumber = jtxtRoutingNumber.getText();
        String accountNumber = jtxtAccountNumber.getText();
        String bankName = jtxtBankName.getText();
        if (routingNumber.isBlank() | bankName.isBlank() | accountNumber.isBlank()){
        JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Error", JOptionPane.ERROR_MESSAGE) ;
        // pause until the user closes the dialog.
        return;
        }
        try {
            balance = Integer.parseInt (jtxtBalance.getText ());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "please check the balance input.", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
        }
            Account a = accountDirectory.addAccount();
            a.setRoutingNumber (routingNumber);
            a.setAccountNumber (accountNumber);
            a.setBankName (bankName) ;
            a.setBalance(balance) ;
            JOptionPane.showMessageDialog(this, "Account successfully created.", "Information", JOptionPane. INFORMATION_MESSAGE) ;
            jtxtRoutingNumber.setText("");
            jtxtAccountNumber.setText("");
            jtxtBankName.setText("");
            jtxtBalance.setText("");
    }//GEN-LAST:event_jbtnCreateActionPerformed

    private void jtxtAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAccountNumberActionPerformed

    private void jtxtBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBankNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout. previous (userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jbtnCreate;
    private javax.swing.JLabel jlblAccountNumber;
    private javax.swing.JLabel jlblBalance;
    private javax.swing.JLabel jlblBankName;
    private javax.swing.JLabel jlblRoutingNumber;
    private javax.swing.JTextField jtxtAccountNumber;
    private javax.swing.JTextField jtxtBalance;
    private javax.swing.JTextField jtxtBankName;
    private javax.swing.JTextField jtxtRoutingNumber;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
