/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AccountManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Account;
import model.AccountDirectory;

/**
 *
 * @author hardishah
 */
public class ManageAccountsJPanel extends javax.swing.JPanel {

        JPanel userProcessContainer;
        AccountDirectory accountDirectory;
    /**
     * Creates new form ManageAccountsJPanel
     */
    public ManageAccountsJPanel(JPanel container, AccountDirectory directory) {
        userProcessContainer = container;
        accountDirectory = directory;
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnSearch = new javax.swing.JButton();
        jbtnViewDetails = new javax.swing.JButton();
        jbtnDeleteAccount = new javax.swing.JButton();
        jtxtSearchBox = new javax.swing.JTextField();
        jbtnBack = new javax.swing.JButton();
        jlblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblAccounts = new javax.swing.JTable();

        jbtnSearch.setText("Search");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        jbtnViewDetails.setText("View Details");
        jbtnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewDetailsActionPerformed(evt);
            }
        });

        jbtnDeleteAccount.setText("Delete Account");
        jbtnDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteAccountActionPerformed(evt);
            }
        });

        jtxtSearchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSearchBoxActionPerformed(evt);
            }
        });

        jbtnBack.setText("<<< Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jlblTitle.setText("Manage Account");

        jtblAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bank Name", "Routing Number", "Account Number", "Balance"
            }
        ));
        jScrollPane1.setViewportView(jtblAccounts);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271)
                .addComponent(jlblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnViewDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnDeleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jtxtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnBack, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblTitle, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnViewDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnDeleteAccount)
                .addContainerGap(196, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
                userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout. previous (userProcessContainer);
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        // TODO add your handling code here:
        if (!jtxtSearchBox.getText().isBlank()) {
            String accountNumber = jtxtSearchBox.getText();
            Account foundAccount = accountDirectory.searchAccount (accountNumber);
            if (foundAccount != null) {
            ViewAccountJPanel panel = new ViewAccountJPanel(userProcessContainer,accountDirectory, foundAccount);
            userProcessContainer.add ("ViewAccountJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout ();
            layout.next(userProcessContainer);
            } else {
                JOptionPane.showMessageDialog(null, "Account not found. Please check the account number and try again.");
            }
            } else {
    
    JOptionPane.showMessageDialog(null, "Please type the account number to view.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void jbtnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtblAccounts.getSelectedRow();
        if (selectedRow >= 0) {
            Account selectedAccount = (Account) jtblAccounts.getValueAt (selectedRow, 0);
            ViewAccountJPanel panel = new ViewAccountJPanel (userProcessContainer, accountDirectory, selectedAccount);
            userProcessContainer.add ("ViewAccountJPanel", panel) ;
            CardLayout layout = (CardLayout) userProcessContainer.getLayout ();
            layout.next (userProcessContainer);
        // We want to open ViewJPanel here for the selected account
        } else {
        JOptionPane.showMessageDialog(null, "Please select an account from the list to view.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtnViewDetailsActionPerformed

    private void jbtnDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteAccountActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtblAccounts.getSelectedRow();
        if (selectedRow >= 0) {
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected account?", "Warning",dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
        Account selectedAccount = (Account) jtblAccounts.getValueAt (selectedRow, 0);
        accountDirectory.deleteAccount (selectedAccount);
        populateTable();
}
} else {
            JOptionPane.showMessageDialog(null, "Please select an account from the list.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtnDeleteAccountActionPerformed

    private void jtxtSearchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSearchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSearchBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnDeleteAccount;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnViewDetails;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JTable jtblAccounts;
    private javax.swing.JTextField jtxtSearchBox;
    // End of variables declaration//GEN-END:variables
public void populateTable() {
    DefaultTableModel model = (DefaultTableModel) jtblAccounts.getModel();
    model. setRowCount (0) ;
    for (Account a : accountDirectory.getAccounts()) {
    Object [] row = new Object [4];
    row[0] = a;
    row[1] = a. getRoutingNumber ();
    row[2] = a.getAccountNumber ();
    row[3] = String.valueOf(a.getBalance ());
    model. addRow (row);

    }
}
}
